spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/fty
        username: cheolho
        password: cheolho
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org:
            hibernate.type.descriptor.sql.BasicBinder: TRACE
            hibernate.SQL: DEBUG
            springframework:
                web:
                    filter: debug
