spring:
    datasource:
        # H2 using memory:
        url: jdbc:h2:mem:food-to-you
        # H2 using file:
        #url: jdbc:h2:~/h2/food-to-you
        driver-class-name: org.h2.Driver
        username: charlie
        password: charlie
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false

logging:
    level:
        org:
            hibernate.type.descriptor.sql.BasicBinder: TRACE
            hibernate.SQL: DEBUG
            springframework:
                web:
                    filter: debug
