spring:
  datasource:
    # H2 using memory:
    url: jdbc:h2:mem:food-to-you
    # H2 using file:
    #url: jdbc:h2:~/h2/food-to-you
    driver-class-name: org.h2.Driver
    username: charlie
    password: charlie
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    org:
      springframework:
        web:
          filter: debug